# Generated by Django 5.0.6 on 2024-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(default='default content'),
            preserve_default=False,
        ),
    ]
